import type { Initiative, Quarter } from "./types";

const createInitiative = (
  id: string,
  stream: any,
  workType: any,
  itBusinessPartner: any,
  workName: string,
  priority: any,
  classification: any,
  assignedQuarter?: Quarter,
): Initiative => {
  const hours = { q1: 0, q2: 0, q3: 0, q4: 0, total: 0 };

  if (assignedQuarter) {
    hours[assignedQuarter] = 100; // Asignamos 100 horas por defecto al trimestre asignado
    hours.total = 100;
  }

  return {
    id,
    stream,
    workType,
    itBusinessPartner,
    workName,
    priority,
    classification,
    hours,
  };
};

export const INITIAL_INITIATIVES: Initiative[] = [
  // --- Operative Initiatives (Backlog - 0 Horas) ---
  createInitiative(
    "init-op-001",
    "Finance",
    "Operative Initiative",
    "Andy Sánchez",
    "Finance Dashboard PowerBI",
    "Nice to Have",
    "Report",
  ),
  createInitiative(
    "init-op-002",
    "HR",
    "Operative Initiative",
    "Andy Sánchez",
    "Onboarding App V2",
    "Must Have",
    "Power App",
  ),
  createInitiative(
    "init-op-003",
    "IT",
    "Operative Initiative",
    "Andy Sánchez",
    "Legacy System Migration",
    "Must Have",
    "Project",
  ),
  createInitiative(
    "init-op-004",
    "HSE",
    "Operative Initiative",
    "Andy Sánchez",
    "Safety Incident Tracker",
    "Must Have",
    "PWA",
  ),
  createInitiative(
    "init-op-005",
    "Sales",
    "Operative Initiative",
    "Andy Sánchez",
    "Sales Dashboard Maintenance",
    "Must Have",
    "Report",
  ),
  createInitiative(
    "init-op-006",
    "Finance",
    "Operative Initiative",
    "Andy Sánchez",
    "Tax Calculation Bot",
    "Must Have",
    "AI",
  ),
  createInitiative(
    "init-op-007",
    "Quality",
    "Operative Initiative",
    "Andy Sánchez",
    "Lab Data Connector",
    "Must Have",
    "Power App",
  ),
  createInitiative(
    "init-op-008",
    "HR",
    "Operative Initiative",
    "Andy Sánchez",
    "Payroll System Patch",
    "Must Have",
    "Project",
  ),
  createInitiative(
    "init-op-009",
    "SMO",
    "Operative Initiative",
    "Andy Sánchez",
    "PMO Dashboard Updates",
    "Must Have",
    "Report",
  ),
  createInitiative(
    "init-op-010",
    "Sales",
    "Operative Initiative",
    "Andy Sánchez",
    "CRM Data Cleanup",
    "Nice to Have",
    "Project",
  ),
  createInitiative(
    "init-op-011",
    "SCM - Logistics",
    "Operative Initiative",
    "Andy Sánchez",
    "Fleet Tracking App",
    "Must Have",
    "PWA",
  ),
  createInitiative(
    "init-op-012",
    "IT",
    "Operative Initiative",
    "Andy Sánchez",
    "Helpdesk Chatbot",
    "Nice to Have",
    "AI",
  ),
  createInitiative(
    "init-op-013",
    "SMO",
    "Operative Initiative",
    "Andy Sánchez",
    "Meeting Room Booking App",
    "Nice to Have",
    "Power App",
  ),
  createInitiative(
    "init-op-014",
    "Marketing",
    "Operative Initiative",
    "Andy Sánchez",
    "Campaign ROI Tracker",
    "Nice to Have",
    "Report",
  ),
  createInitiative(
    "init-op-015",
    "Formulation",
    "Operative Initiative",
    "Andy Sánchez",
    "Sample Tracking System",
    "Must Have",
    "Power App",
  ),
  createInitiative(
    "init-op-016",
    "HR",
    "Operative Initiative",
    "Andy Sánchez",
    "Employee Feedback Pulse",
    "Nice to Have",
    "PWA",
  ),

  // --- SP Company Projects (5 Total - Distribuidos en Q1-Q4) ---
  createInitiative(
    "init-cp-001",
    "Sales",
    "SP Company Project",
    "Andy Sánchez",
    "Sales Force Automation AI",
    "Must Have",
    "AI",
    "q1",
  ),
  createInitiative(
    "init-cp-002",
    "Marketing",
    "SP Company Project",
    "Andy Sánchez",
    "Customer 360 View",
    "Nice to Have",
    "Project",
    "q2",
  ),
  createInitiative(
    "init-cp-003",
    "SMO",
    "SP Company Project",
    "Andy Sánchez",
    "Strategic Planning Tool",
    "Nice to Have",
    "Power App",
    "q3",
  ),
  createInitiative(
    "init-cp-004",
    "IT",
    "SP Company Project",
    "Andy Sánchez",
    "Cloud Infrastructure Upgrade",
    "Must Have",
    "Project",
    "q4",
  ),
  createInitiative(
    "init-cp-005",
    "HSE",
    "SP Company Project",
    "Andy Sánchez",
    "Sustainability Report 2024",
    "Must Have",
    "Report",
    "q1",
  ),

  // --- SP Functional Projects (10 Total - Distribuidos en Q1-Q4) ---
  createInitiative(
    "init-fp-001",
    "SCM - Logistics",
    "SP Functional Project",
    "Andy Sánchez",
    "Warehouse Digital Twin",
    "Must Have",
    "Project",
    "q1",
  ),
  createInitiative(
    "init-fp-002",
    "Quality",
    "SP Functional Project",
    "Andy Sánchez",
    "Quality Control AI Vision",
    "Must Have",
    "AI",
    "q2",
  ),
  createInitiative(
    "init-fp-003",
    "Procurement",
    "SP Functional Project",
    "Andy Sánchez",
    "Supplier Portal Upgrade",
    "Must Have",
    "Project",
    "q3",
  ),
  createInitiative(
    "init-fp-004",
    "Marketing",
    "SP Functional Project",
    "Andy Sánchez",
    "Marketing Automation V2",
    "Nice to Have",
    "Project",
    "q4",
  ),
  createInitiative(
    "init-fp-005",
    "SCM - Operations",
    "SP Functional Project",
    "Andy Sánchez",
    "Production Line IoT",
    "Nice to Have",
    "PWA",
    "q1",
  ),
  createInitiative(
    "init-fp-006",
    "Finance",
    "SP Functional Project",
    "Andy Sánchez",
    "Financial Forecasting AI",
    "Must Have",
    "AI",
    "q2",
  ),
  createInitiative(
    "init-fp-007",
    "HR",
    "SP Functional Project",
    "Andy Sánchez",
    "Global HR Portal",
    "Nice to Have",
    "PWA",
    "q3",
  ),
  createInitiative(
    "init-fp-008",
    "IT",
    "SP Functional Project",
    "Andy Sánchez",
    "DevOps Pipeline Automation",
    "Must Have",
    "Project",
    "q4",
  ),
  createInitiative(
    "init-fp-009",
    "Sales",
    "SP Functional Project",
    "Andy Sánchez",
    "Sales Enablement App",
    "Nice to Have",
    "Power App",
    "q2",
  ),
  createInitiative(
    "init-fp-010",
    "Marketing",
    "SP Functional Project",
    "Andy Sánchez",
    "Digital Asset Management",
    "Must Have",
    "Project",
    "q3",
  ),
];

export const QUARTER_LIMITS = {
  q1: 102,
  q2: 408,
  q3: 408,
  q4: 408,
  total: 1326,
};
